#pragma once

#include <TString.h>
#include <iostream>
#include <vector>

// This class can be used to calculate the Erel spectra from a given data.
// The data should come in a std::vector for each particle, for our case
// Energy of the neutron and energy of the fragment.
// Since the data retrieval will highly depend on the data type (simulated
// or experimental), the GetData method will be virtual and will be separately
// implemented for experimental data and for simulated data.

class IERelCalculator
{
public:
    virtual ~IERelCalculator() = default;
    virtual void getData(const std::vector<TString> inputFiles, const std::vector<int> particles) = 0;
    void Calculate()
    {
        for (const auto &evt : fKinematics)
        {
            const double m1 = evt[0], px1 = evt[1], py1 = evt[2], pz1 = evt[3];
            const double m2 = evt[4], px2 = evt[5], py2 = evt[6], pz2 = evt[7];

            const double p1s = px1 * px1 + py1 * py1 + pz1 * pz1;
            const double p2s = px2 * px2 + py2 * py2 + pz2 * pz2;

            const double E1 = std::sqrt(m1 * m1 + p1s);
            const double E2 = std::sqrt(m2 * m2 + p2s);

            const double Et = E1 + E2;
            const double Pxt = px1 + px2;
            const double Pyt = py1 + py2;
            const double Pzt = pz1 + pz2;
            const double Pt2 = Pxt * Pxt + Pyt * Pyt + Pzt * Pzt;

            const double Minv = std::sqrt(std::max(0.0, Et * Et - Pt2));
            const double Erel_GeV = Minv - (m1 + m2);
            fErel.push_back(Erel_GeV * 1e3);

        }
    }

    void plotErel()
    {
        auto *h = new TH1F("h", "h", 200, 0, 3);

        for (auto const &erel : fErel)
        {
            h->Fill(erel);
        }

        h->Draw();
    }

protected:
    std::vector<std::vector<double>> fKinematics;
    std::vector<double> fErel;
};

// First implementation: without neuland response
class ERelSimCalculator : public IERelCalculator
{
public:
    void getData(const std::vector<TString> inputFiles, const std::vector<int> particles) override
    {

        // Vector to store the kinematic information to calculate the Erel
        std::vector<std::vector<double>> Kinematics;
        std::vector<double> iKinematics;

        // Get the input file with the data
        TString repopath = getenv("repopath");
        TString absPath = repopath + "/results/sim/";

        // Chain all files
        TChain chain("evt");
        for (const auto &f : inputFiles)
        {
            chain.Add(absPath + f);
        }

        // Reader
        TTreeReader reader(&chain);

        // Get branch mctrack
        TTreeReaderArray<R3BMCTrack> tracks(reader, "MCTrack");

        // Event loop
        while (reader.Next())
        {
            std::vector<double> iKinematics;

            for (const auto &tr : tracks)
            {
                // Only O and the neutron generated by the generator
                if (tr.GetMotherId() != -1)
                    continue;

                // Keep the event only if it's our particle of interest
                for (auto const &part : particles)
                {
                    if (part == tr.GetPdgCode())
                    {
                        iKinematics.push_back(tr.GetMass());
                        iKinematics.push_back(tr.GetPx());
                        iKinematics.push_back(tr.GetPy());
                        iKinematics.push_back(tr.GetPz());
                    }
                }
            }

            // Save it if we have two particles
            if (iKinematics.size() != 8)
            {
                std::cerr << "[ERROR] You are not storing the kinematics for all particles"
                          << " (got " << iKinematics.size() << " values)" << std::endl;
            }
            else
            {
                fKinematics.push_back(std::move(iKinematics));
            }

        }
    }
};

class ERelExpCalculator : public IERelCalculator
{
public:
    void getData(const std::vector<TString> inputFiles, const std::vector<int> particles) override
    {

        std::cerr << "[ERROR] getData() has not been implemented yet for experimental data" << std::endl;
        fKinematics = {{}};
    }
};